OpenAtomFoundation/xupercore

- kernel/engines/xuperos/chain.go
- kernel/engines/xuperos/def/interface.go
- kernel/engines/xuperos/engine.go
- kernel/engines/xuperos/mock/rely_agent.go
- kernel/engines/xuperos/rely_agent.go
xuperos support rely agent.
1.It is convenient to develop in parallel.
2.Unit test is friendly.
3.Easy to expand.
> xuperos support rely agent

- bcs/consensus/tdpos/tdpos.go
- bcs/consensus/xpoa/xpoa.go
- kernel/consensus/base/common/common.go
- kernel/consensus/base/driver/chained-bft/smr.go
- kernel/consensus/base/driver/chained-bft/smr_test.go
Fix the bug when restarting the system, in which case the new block will carry empty signatures.
> Consensus:fix the bugs in InitQCTree and NewSmr.

- bcs/ledger/xledger/state/xmodel/xmodel_iterator.go
- kernel/contract/sandbox/mem_xmodel.go
- kernel/contract/sandbox/mem_xmodel_test.go
目前的XuperModel迭代器返回的key结构是`bucket/key`，应该把`bucket/`去掉。
> kernel/contract: fix wrong key for iterator

- bcs/ledger/xledger/ledger/ledger_hash.go
- bcs/ledger/xledger/ledger/ledger_hash_test.go
减少merkle算法的内存分配
一个区块里面的交易多了之后，生成默克尔树就比较耗时，这个提交减少了内存分配的次数，内存分配主要在sha256的生成上，每个double sha256都要进行2次分配。
这个PR使用了[arena](https://en.wikipedia.org/wiki/Region-based_memory_management)分配算法，一次性申请够所有的内存，再在每次计算sha256的时候单独分配, 另外使用了零分配的sha256函数来辅助计算sha256 
修复前:
```
BenchmarkNormalMerkle-160            100          11672176 ns/op         2067500 B/op      30017 allocs/op
```
修复后：
```
BenchmarkNormalMerkle-160            100          10394688 ns/op         1835604 B/op          5 allocs/op
```
对于一个`10000`个交易的区块，内存分配次数从`30017`降到了`5`
> ledger: reduce the memory allocation of the Merkle tree generation algorithm

- bcs/network/p2pv1/client.go
- bcs/network/p2pv1/conn.go
- bcs/network/p2pv1/filter.go
- bcs/network/p2pv1/handler.go
- bcs/network/p2pv1/server.go
Add router in static-node mode.
Nodes can refresh their router info by the function GetPeerInfo.
Use testnet and xfront.
> p2pv1: change dynamic-nodes connections to static-node connections in static-node mode.

- bcs/ledger/xledger/ledger/ledger.go
- bcs/network/p2pv2/client.go
- kernel/engines/xuperos/miner/miner.go
- kernel/engines/xuperos/miner/sync.go
- kernel/engines/xuperos/net/net_event.go
将原来p2p中获取tx的接口从`QueryTx`替换成`QueryTransaction`，从而避免了每个tx需要再查询一下区块头。
> miner: speed up GetBlockTx

- bcs/ledger/xledger/state/state.go
- bcs/ledger/xledger/tx/mempool.go
- bcs/ledger/xledger/tx/mempool_test.go
- bcs/ledger/xledger/tx/tx.go
- kernel/network/p2p/dispatcher.go
修改 confirem tx 耗时太长，以及删除 p2p 中的多余代码。
> fix confirm tx and p2p map cocurrent read

- bcs/ledger/xledger/tx/mempool.go
从磁盘加载未确认交易时，mempool 添加交易时如果此交易非孤儿交易，那么要检查此交易得所有子交易，判断有没有孤儿交易可以移动到未确认交易表。之前因为同样遍历了子交易得父交易，可能导致将虚拟的孤儿交易加入到未确认交易表。
> fix load tx from disk faild and make merkle tree hash panic

- bcs/ledger/xledger/tx/mempool.go
修复裁剪账本或者程序重启时，从磁盘加载未确认交易时 mempool 导致 panic 问题。
> fix load tx from disk faild and make merkle tree hash panic (#270)

- bcs/consensus/xpoa/common.go
- bcs/consensus/xpoa/common_test.go
- bcs/consensus/xpoa/kernel_contract.go
- bcs/consensus/xpoa/kernel_contract_test.go
- bcs/consensus/xpoa/schedule.go
- bcs/consensus/xpoa/xpoa.go
- kernel/consensus/base/driver/chained-bft/smr.go
consensus: make smr run with a single validator. (#284) 
xpoa: parameter version works compatibly with int and string type (#286)
> Cherry-pick commit #284 & #286 to v5.2

- bcs/consensus/xpoa/xpoa.go
- bcs/network/p2pv1/server.go
兼容容器环境, 监听 ":port";
兼容容器环境, 监听的"127.0.0.1:47101" 存在问题, 修改为监听 ": 47101"
兼容容器环境, 监听的"127.0.0.1:47101" 存在问题, 修改为监听 ": 47101"
> 兼容容器环境, 监听 ":port"

- bcs/network/p2pv2/stream_pool.go
代码中关于peerids的获取是经过kaddht句柄从底层libp2p库获取到然后经过multi过滤器过滤，此处暂未处理获取peerids的流程，仅当上述错误出现时由warn级别改为info日志级别
【日志】【优化】tdpos共识，日志频繁刷跟自己建立p2p连接的日志，需优化
仅当"dial to self attempted"错误出现时由warn级别改为info日志级别
部署运行，查看xchain.log.wf日志中是否出现warn级别的"dial to self attempted"日志
> 问题：日志中出现大量warn级别"dial to self attempted"的优化

- bcs/network/p2pv2/stream_pool.go
p2p连接大量warn级别的"dial to self attempted"日志
将"dial to self attempted"日志级别修改为info级别，该日志不会输出的xchain.log.wf当中
检测是否还会出现warn级别的"dial to self attempted"日志
> 问题：p2p连接显示"dial to self attempted"错误 (#298)

- bcs/ledger/xledger/state/state.go
- bcs/ledger/xledger/state/utxo/utxo.go
- bcs/ledger/xledger/state/utxo/utxo_test.go
当utxo cache设置太小时，非旷工节点执行一个区块时有可能执行失败。解决方案是针对执行区块时将区块内所有交易的 utxo 缓存起来。
> fix play block failed when utxo cache too small

- bcs/consensus/tdpos/common.go
- bcs/consensus/xpoa/xpoa.go
问题：poa和pos类共识配置如果init_proposer参数为空会导致panic或者节点无法出块的错误
解决：poa和pos类共识实例创建的时候增加init_proposer参数校验，校验失败返回错误
poa和pos类共识实例创建的时候增加init_proposer参数校验，校验失败返回错误
升级到poa和pos类共识时desc文件内部缺少init_proposer参数会导致共识升级失败
错误日志标签：
1. 升级到tdpos：init_proposer is required 或者 init_proposer["1"] is required
2. 升级到poa：init_proposer.address is required
> 问题：poa和pos类共识配置如果init_proposer参数为空会导致panic或者节点无法出块的错误

- bcs/consensus/tdpos/common.go
- bcs/consensus/xpoa/xpoa.go
poa和pos类共识配置如果init_proposer参数为空会导致panic或者节点无法出块的错误
增加参数校验
poa和pos类共识实例创建的时候增加init_proposer参数校验，校验失败返回错误
升级到poa和pos类共识时desc文件内部缺少init_proposer参数会导致共识升级失败
错误日志标签：
升级到tdpos：init_proposer is required 或者 init_proposer["1"] is required
升级到poa：init_proposer.address is required
> 问题：poa和pos类共识配置如果init_proposer参数为空会导致panic或者节点无法出块的错误 (#301)

- bcs/ledger/xledger/state/tx_verification.go
状态机在walk验证区块执行timer合约时检查autoTx.TxOutputsExt为空时返回错误，导致停止出块
区块验证时不检查timer_task合约执行的读写集输出
节点验证区块timer合约结果集输出为空时，仍可继续出块
> 状态机在walk验证区块执行timer合约时检查autoTx.TxOutputsExt为空时返回错误，导致停止出块

- bcs/ledger/xledger/state/tx_verification.go
状态机在walk验证区块执行timer合约时检查autoTx.TxOutputsExt为空时返回错误，导致停止出块
区块验证时不检查timer_task合约执行的读写集输出
节点验证区块timer合约结果集输出为空时，仍可继续出块
> 状态机在walk验证区块执行timer合约时检查autoTx.TxOutputsExt为空时返回错误，导致停止出块 (#308)

- kernel/consensus/pluggable_consensus.go
不允许从pow共识升级为其他共识
升级共识时，如果当前共识时pow则直接返回升级失败
当前共识为pow共识，升级共识会显示失败
> Fix consensus

- .github/workflows/backport.yml
Add auto backporting support. 
Any pull request with label `backport <branch name> ` will cause a new pull request  to release branch automatically.
for example if you wanna backport your pull request to release-v5.1, just add `backport release-v5.1`  label after pr is created. 
see https://github.com/tibdex/backport for more details 
> add auto backporting support

- bcs/consensus/tdpos/schedule.go
- bcs/consensus/tdpos/schedule_test.go
- bcs/consensus/tdpos/tdpos.go
- kernel/consensus/base/driver/chained-bft/saftyrules.go
- kernel/consensus/base/driver/chained-bft/smr.go
- kernel/consensus/base/driver/chained-bft/smr_test.go
- kernel/engines/xuperos/miner/miner.go
通过系统合约进行共识提案投票或者变更候选人集合后，poa和pos类共识偶现停止出块
1. miner中添加同步最长链检查，如果CompeteMaster后链高度变化，则需要重新计算CompeteMaster
2. tdpos中计算calHisValidators时获取上一轮term的最后一个区块
3. tdpos和chained-bft中添加部分日志
> Fixed the poa and pos consensus stopped producing blocks after operations such as proposal changes

- kernel/engines/xuperos/chain.go
PostTx 时检查交易是否已经存在账本或者未确认交易表中，在特殊情况下不加此检查会导致区块打包失败。
> add check tx already in db when post tx

- bcs/contract/evm/creator.go
- bcs/contract/xvm/code_manager_test.go
- bcs/ledger/xledger/state/tx_verification.go
- bcs/ledger/xledger/state/xmodel/xmodel_snapshot.go
- kernel/consensus/mock/mock_pluggable_consensus.go
- kernel/contract/bridge/code_provider.go
- kernel/contract/bridge/context.go
- kernel/contract/bridge/contract_manager.go
- kernel/contract/bridge/vm.go
- kernel/contract/bridge/xbridge.go
- kernel/contract/context.go
- kernel/contract/sandbox/mem_xmodel.go
- kernel/contract/sandbox/xmcache.go
- kernel/contract/state.go
- kernel/ledger/interface.go
…e in the same block
evm合约部署和调用如果在同一区块中，会导致同步区块执行调用合约时无法读取到合约code
evm合约执行时，如果是区块内交易则从本地区块级别缓存中读取数据
> Fix the error that evm contract deployment and calling transaction are in the same block

- kernel/contract/sandbox/xmcache.go
Fix the problem of iterating panic when the parameter is wrong
> Fix the problem of iterating panic when the parameter is wrong

- bcs/ledger/xledger/state/utxo/spin_lock.go
当只读key的交易post到节点时，spinlock 中没有将只读的key从map中删除，最终会导致oom。
see #379
> fix spinlock refCounter oom when readonly key tx post

- bcs/network/p2pv2/client.go
> fix get peerID from account cache

- .golangci.yaml
- .pre-commit-config.yaml
- bcs/consensus/tdpos/kernel_contract_test.go
- kernel/engines/xuperos/asyncworker/asyncworker_impl.go
- kernel/engines/xuperos/asyncworker/asyncworker_test.go
- kernel/engines/xuperos/chain.go
- kernel/engines/xuperos/engine.go
- kernel/engines/xuperos/engine_test.go
- Enable go-lint for local pre-commit
- Fix errors in kernel/engines/xuperos/asyncworker
see #399
> Enable go-lint for local pre-commit

- bcs/contract/evm/abi/abi.go
- bcs/contract/evm/address.go
- kernel/permission/acl/ptree/ptree.go
- kernel/permission/acl/utils/utils.go
> Refine readability

- bcs/network/p2pv2/client.go
dht 中 record 默认缓存时间为36h，xupercore中一直缓存，最终导致节点重启后，在网络中 SearchValue 失败，最终导致不能同步区块。本次将 xupercore 中缓存改为1h，每隔1h去网络中查询并更新一次。
> add account to peerID cache expiration
