OpenAtomFoundation/xupercore

cmd/xchain/cmd/startup.go, cmd/xchain/cmd/version.go, go.mod, kernel/engines/factory.go, kernel/engines/xuperos/chain.go, kernel/engines/xuperos/def/interface.go, kernel/engines/xuperos/engine.go, kernel/engines/xuperos/miner.go, kernel/engines/xuperos/net/net.go, kernel/engines/xuperos/rely_agent.go, kernel/engines/xuperos/tx.go, server/context/context.go, server/rpc/api.go, server/rpc/manage.go, server/rpc/rpc.go
Fix framework bug,it can be compiled and passed.
=> fix framework bug

lib/cache/lru_cache.go
=> add lru cache

kernel/common/xconfig/conf/env.yaml, kernel/common/xconfig/config.go, kernel/common/xutils/utils.go, kernel/common/xutils/utils_test.go
Update root path set priority.
=> update root path set priority

bcs/ledger/xledger/def/const.go, bcs/ledger/xledger/def/context.go, bcs/ledger/xledger/def/interface.go, bcs/ledger/xledger/ledger/ledger.go
=> update ledger context

kernel/engines/xuperos/agent/rely.go, kernel/engines/xuperos/chain.go, kernel/engines/xuperos/ledger/govern.go
=> xuperos:fix bug

kernel/common/xaddress/address.go, kernel/engines/xuperos/agent/chaincore.go, kernel/engines/xuperos/agent/rely.go, kernel/engines/xuperos/chain.go, kernel/engines/xuperos/commom/context.go, kernel/engines/xuperos/commom/interface.go
upgrade xuperos rely interface
=> upgrade xuperos rely interface

kernel/engines/xuperos/agent/ledger.go, kernel/ledger/def.go
=> xuperos:add ledger agent

kernel/consensus/context/context.go, kernel/consensus/def/def.go, kernel/engines/xuperos/agent/ledger.go, kernel/engines/xuperos/agent/rely.go, kernel/engines/xuperos/chain.go, kernel/ledger/def.go
xuperos:upgrade consensus rely.
=> xuperos:upgrade consensus rely

kernel/permission/acl/context/context.go, kernel/permission/acl/manager.go
acl:fix contract registry bug.
=> acl:fix contract registry bug

bcs/consensus/mock/mock_consensus.go, bcs/consensus/pow/pow.go, bcs/consensus/pow/pow_test.go, bcs/consensus/single/single.go, bcs/consensus/single/single_test.go, bcs/consensus/xpoa/xpoa.go, kernel/consensus/base/driver/chained-bft/crypto/crypto.go, kernel/consensus/base/driver/chained-bft/main/chained-main.go, kernel/consensus/base/driver/chained-bft/smr.go, kernel/consensus/base/impl_interface.go, kernel/consensus/context/context.go, kernel/consensus/mock/mock_pluggable_consensus.go, kernel/consensus/pluggable_consensus.go, kernel/consensus/pluggable_consensus_test.go
Fix unit tests' bugs due to the changes in the context of pluggable consensus.
=> Consensus: fix unit tests.

kernel/engines/xuperos/README.md
=> README:Add external interface

kernel/engines/xuperos/miner/miner.go
=> xuperos:add pow calculate

Makefile, kernel/engines/xuperos/agent/block.go, kernel/engines/xuperos/miner/miner.go
=> xuperos:fix miner logic

Makefile, example/xchain/auto/build.sh, example/xchain/cmd/xchain/cmd/startup.go, example/xchain/cmd/xchain/cmd/version.go, example/xchain/common/def/def.go, example/xchain/service/rpc/manage.go, kernel/engines/xuperos/common/const.go, kernel/engines/xuperos/config/config.go
=> fix import cycle bug

bcs/ledger/xledger/ledger/ledger.go, bcs/ledger/xledger/state/utxo/txhash/encode.go, example/xchain/cmd/xchain/cmd/version.go, example/xchain/common/version/version.go, kernel/permission/acl/ak_2_account.go, kernel/permission/acl/base/interface.go, kernel/permission/acl/context/context.go, kernel/permission/acl/contract.go, kernel/permission/acl/manager.go, kernel/permission/acl/utils/utils.go
=> fix compile bug

bcs/consensus/tdpos/schedule.go, bcs/consensus/tdpos/tdpos.go, bcs/consensus/xpoa/common.go, bcs/consensus/xpoa/common_test.go, bcs/consensus/xpoa/schedule.go, bcs/consensus/xpoa/schedule_test.go, bcs/consensus/xpoa/status.go, bcs/consensus/xpoa/xpoa.go, kernel/consensus/base/common/common.go, kernel/consensus/base/driver/chained-bft/context.go, kernel/consensus/base/driver/chained-bft/saftyrules.go, kernel/consensus/base/driver/chained-bft/smr.go, kernel/consensus/pluggable_consensus.go
Consensus::fix bugs during test xpoa.
=> Consensus::fix bugs during test xpoa.

bcs/ledger/xledger/ledger/genesis.go, kernel/engines/xuperos/common/error.go, kernel/engines/xuperos/net/error.go, kernel/engines/xuperos/reader/utxo_info.go
=> gofmt code

bcs/consensus/tdpos/tdpos.go, bcs/consensus/xpoa/schedule.go, bcs/consensus/xpoa/xpoa.go, kernel/consensus/base/common/common.go, kernel/consensus/base/driver/chained-bft/context.go, kernel/consensus/base/driver/chained-bft/saftyrules.go, kernel/consensus/base/driver/chained-bft/smr.go, kernel/consensus/base/driver/chained-bft/smr_test.go
Fix the vote bugs and renew the vote id in smr.
=> Consensus::fix vote bugs in smr.

bcs/ledger/xledger/config/config.go, bcs/ledger/xledger/def/const.go, bcs/ledger/xledger/ledger/context.go, bcs/ledger/xledger/ledger/ledger.go, bcs/ledger/xledger/state/context/context.go, bcs/ledger/xledger/state/state.go, bcs/ledger/xledger/state/utxo/utxo.go, example/xchain/cmd/xchain/cmd/startup.go
=> fix some bugs

bcs/consensus/tdpos/common.go, bcs/consensus/tdpos/tdpos.go, example/xchain/auto/control.sh, example/xchain/data/genesis/single.json, example/xchain/service/rpc/manage.go, kernel/consensus/pluggable_consensus.go, kernel/engines/xuperos/agent/ledger.go, kernel/engines/xuperos/chain.go, kernel/engines/xuperos/engine.go
Fix consensus config marshal bug.
=> fix consensus config marshal bug

bcs/consensus/xpoa/schedule.go, bcs/consensus/xpoa/xpoa.go, kernel/consensus/base/driver/chained-bft/context.go, kernel/consensus/base/driver/chained-bft/pacemaker.go, kernel/consensus/base/driver/chained-bft/smr.go
Delete new-view message, and fix the other bugs in smr and xpoa.
=> Consensus::fix smr bugs and xpoa bugs.

bcs/consensus/xpoa/common.go, bcs/consensus/xpoa/schedule.go, bcs/consensus/xpoa/status.go, bcs/consensus/xpoa/xpoa.go, kernel/consensus/base/common/common.go, kernel/consensus/base/driver/chained-bft/context.go
Fix value unmarshal in xpoa according to xpoa_validators.cc.
=> Consensus::fix value unmarshal in xpoa according to xpoa_validators.cc.

bcs/consensus/xpoa/common.go, bcs/consensus/xpoa/schedule.go, bcs/consensus/xpoa/xpoa.go, kernel/consensus/base/driver/chained-bft/saftyrules.go, kernel/consensus/base/driver/chained-bft/smr.go
Fix bugs in xpoa when add or delete the parameters in the xpoa contract.
=> Consensus::fix several bugs in xpoa and smr.

example/xchain/models/chain_handle.go, kernel/engines/xuperos/chain.go, kernel/engines/xuperos/common/error_test.go, kernel/engines/xuperos/common/interface.go, kernel/engines/xuperos/engine.go, kernel/engines/xuperos/miner/miner.go, kernel/engines/xuperos/net/client.go, kernel/engines/xuperos/net/net_event.go, kernel/engines/xuperos/reader/chain_info.go, kernel/engines/xuperos/reader/consensus_info.go, kernel/engines/xuperos/reader/contract_info.go, kernel/engines/xuperos/reader/ledger_info.go, kernel/engines/xuperos/reader/utxo_info.go
=> engine:fix some bugs

example/xchain/auto/build.sh, example/xchain/cmd/client/client/client.go, example/xchain/cmd/client/cmd/block.go, example/xchain/cmd/client/cmd/chain.go, example/xchain/cmd/client/cmd/contract.go, example/xchain/cmd/client/cmd/tx.go, example/xchain/cmd/client/cmd/tx/query.go, example/xchain/cmd/client/cmd/tx/submit.go, example/xchain/cmd/client/cmd/version.go, example/xchain/cmd/client/common/global/base.go, example/xchain/cmd/client/common/global/global.go, example/xchain/cmd/client/main.go, lib/utils/utils.go
=> xchain:add query tx cmd

example/xchain/cmd/xchain/cmd/startup.go
=> import xkernel vm

bcs/ledger/xledger/ledger/genesis.go, bcs/ledger/xledger/ledger/ledger.go, bcs/ledger/xledger/state/state.go, bcs/ledger/xledger/utils/utils.go, bcs/network/p2pv1/server.go, bcs/network/p2pv2/server.go, example/xchain/cmd/client/cmd/chain.go, example/xchain/cmd/client/cmd/chain/create.go, example/xchain/cmd/client/cmd/chain/status.go, example/xchain/cmd/client/main.go, kernel/engines/xuperos/net/net_event.go
=> add create ledger command

kernel/engines/xuperos/miner/miner.go, kernel/engines/xuperos/net/net_event.go
=> miner:fix bug

kernel/engines/xuperos/chain.go, kernel/engines/xuperos/miner/miner.go, kernel/engines/xuperos/net/net_event.go
=> miner:fix warn logger

bcs/consensus/tdpos/schedule_test.go, bcs/consensus/tdpos/tdpos.go, bcs/consensus/xpoa/xpoa.go, kernel/consensus/base/driver/chained-bft/context.go, kernel/consensus/base/driver/chained-bft/saftyrules.go, kernel/consensus/base/driver/chained-bft/smr.go
Add a member variable named ledgerState in smr to limit the growth of QC, in which case the difference between the QC and the ledger may cause the ledger to walk steps back greater than 3.
=> Consensus::fix the smr bug.

bcs/consensus/pow/common.go, bcs/consensus/pow/pow.go, bcs/consensus/pow/pow_test.go, bcs/consensus/pow/status.go, bcs/consensus/single/single_test.go, bcs/consensus/tdpos/tdpos.go, kernel/engines/xuperos/miner/miner.go
Fix the bugs in pow & sync blocks.
=> Consensus&SyncBlock::fix bugs.

lib/utils/utils.go
=> utils add GenNonce

bcs/ledger/xledger/ledger/genesis.go, kernel/contract/proposal/propose/propose_contract.go
(1) get config from genesis for distributing govern token when nofee
(2) check vote stop height > trigger height
=> bugFix for governToken & proposal

bcs/ledger/xledger/utils/utils.go, kernel/engines/xuperos/asyncworker/asyncworker_test.go, kernel/engines/xuperos/chain.go, kernel/engines/xuperos/chain_test.go, kernel/engines/xuperos/engine_test.go, kernel/engines/xuperos/parachain/parachain_contract.go
Fix the panic occurred when the engine tries to reload a para-chain that has been created before, as a consequence of the leveldb database instance hasn't closed while a new duplicate one willing to be made.
=> Parachain: fix the bug when reloading a chain existed.

bcs/contract/evm/abi/abi.go, bcs/contract/evm/address.go, bcs/contract/evm/creator.go, go.sum, kernel/contract/bridge/contract_manager.go, kernel/engines/xuperos/chain.go, kernel/engines/xuperos/engine.go, kernel/engines/xuperos/miner/miner.go, lib/storage/kvdb/kvdb_instance.go, lib/storage/kvdb/leveldb/ldb_impl.go
error return in golang is useful for troubleshooting when developing and operating. bad return value style like 
> return nil,nil
when the second value is an error type without any specific reason. it may take you hours even days to find a bug.
return an new error without context info like 
>  if err!=nil{
>    return errors.New("new error")
> }
also confuse you when you wanna find out what happend
=> returen detailed error info for quick troubleshooting when developing and operating 

bcs/ledger/xledger/state/state.go
Fix dead lock for state collect delayed tx and fix rlock to lock for doTxSync.
=> fix dead lock

bcs/network/p2pv2/stream.go
Add write timeout for send p2p message
=> p2p: add timeout for send message

bcs/ledger/xledger/state/state.go, bcs/ledger/xledger/tx/mempool.go, bcs/ledger/xledger/tx/tx.go
回滚区块时，mempool 删除交易需要从 confirmed 列表中也删除。
=> Fix mempool delete confirm tx

bcs/ledger/xledger/state/state.go, bcs/ledger/xledger/tx/mempool.go, bcs/ledger/xledger/tx/tx.go
cherry pick master bug fix about mempool delete confirm tx.
=> Fix mempool delete confirm tx (#247)

bcs/ledger/xledger/utils/utils.go, bcs/network/p2pv1/client.go, bcs/network/p2pv1/conn.go, bcs/network/p2pv1/filter.go, bcs/network/p2pv1/handler.go, bcs/network/p2pv1/server.go, kernel/contract/bridge/syscall_service.go, kernel/engines/xuperos/agent/rely.go, kernel/engines/xuperos/asyncworker/asyncworker_test.go, kernel/engines/xuperos/chain.go, kernel/engines/xuperos/chain_test.go, kernel/engines/xuperos/common/interface.go, kernel/engines/xuperos/engine.go, kernel/engines/xuperos/engine_test.go, kernel/engines/xuperos/parachain/parachain_contract.go, kernel/engines/xuperos/parachain/parachain_manager.go
=> cherry pick for v5.1.1 

bcs/ledger/xledger/config/config.go, bcs/ledger/xledger/state/utxo/utxo.go
=> update utxo cache default size

bcs/consensus/pow/pow.go, bcs/consensus/tdpos/tdpos.go, bcs/consensus/tdpos/tdpos_test.go, bcs/consensus/xpoa/common.go, bcs/consensus/xpoa/schedule.go, bcs/consensus/xpoa/xpoa.go, bcs/consensus/xpoa/xpoa_test.go, kernel/consensus/mock/mock_pluggable_consensus.go, kernel/consensus/pluggable_consensus.go, kernel/consensus/pluggable_consensus_test.go, kernel/contract/kernel.go, kernel/contract/manager/registry_impl.go, kernel/engines/xuperos/chainmgmt.go, kernel/engines/xuperos/net/net_event.go
This PR used to cherry pick features to v5.2.
1）1bdfc064c2eeb765d81f94bb88d9c8f95f43e68c
2）f7860e1dfb1f9525286ede210806e6b98f8601b7
=> Cherry-pick to v5.2 

bcs/consensus/tdpos/tdpos.go, bcs/consensus/tdpos/tdpos_test.go, bcs/consensus/xpoa/common.go, bcs/consensus/xpoa/schedule.go, bcs/consensus/xpoa/xpoa.go, bcs/consensus/xpoa/xpoa_test.go, kernel/consensus/mock/mock_pluggable_consensus.go, kernel/consensus/pluggable_consensus.go, kernel/consensus/pluggable_consensus_test.go, kernel/contract/kernel.go, kernel/contract/manager/registry_impl.go
This PR uesd to cherry-pick feature to v5.1
Commit-ID: f7860e1dfb1f9525286ede210806e6b98f8601b7
=> Cherry-pick consensus upgrade to v5.1

kernel/consensus/pluggable_consensus.go
This pr used to fix consensus version bug.
The version can not rollback to provious version.
=> fix consensus version bug

kernel/consensus/pluggable_consensus.go
This pr used cherry pick bug fix from master.
=> cherry pick consensus version bug fix(#285)

.github/workflows/ci.yml, bcs/contract/native/contract_process_test.go, bcs/ledger/xledger/state/tx_verification.go, bcs/network/p2pv2/server.go, kernel/contract/manager/testdata/features.go, lib/metrics/metrics.go, lib/storage/kvdb/leveldb/ldb_impl.go, lib/storage/kvdb/leveldb/ldb_impl_test.go
style: format existing code and add format check in ci pipeline
=> misc:format existing code and add format check in ci pipeline

bcs/ledger/xledger/tx/mempool.go
修复同一笔交易可能打包到不同链上的bug，由于mempool中有全局变量，Range 是没有判断交易是否属于当前mempool，为了不影响性能，将全局变量作为mempool的字段来解决。
=> fix tx in diff chain

bcs/ledger/xledger/state/state.go, bcs/ledger/xledger/state/utxo/utxo.go, bcs/ledger/xledger/state/utxo/utxo_test.go, bcs/ledger/xledger/tx/mempool.go
cherry pick utxo cacha 太小可能导致执行区块失败以及 mempool 交易可能打包到平行链。
=> Cherrypick bug fix utxocache and mempool tx diff chain

kernel/contract/proposal/propose/propose_contract.go
发起提案相关操作时如果遇到错误，返回的错误信息中有些标识显示错误的操作方法
修复日志中的错误标识信息
修复日志中的错误标识信息
提案相关操作失败时，检查返回的错误信息是否匹配相关操作
=> Fix thaw log

kernel/contract/proposal/propose/propose_contract.go
修复提案相关操作出现错误时，错误内容中的标识信息不准确问题
提案相关操作出现错误时，错误内容中的标识信息不准确
修改内部错误标识信息
提案相关操作出现错误时，校验错误信息内容是否与操作不相关
=> Fix thaw log (#306)

bcs/consensus/pow/pow.go, bcs/consensus/pow/pow_test.go, bcs/consensus/single/single.go, bcs/consensus/single/single_test.go, bcs/consensus/tdpos/tdpos.go, bcs/consensus/tdpos/tdpos_test.go, bcs/consensus/xpoa/xpoa.go, bcs/consensus/xpoa/xpoa_test.go, kernel/consensus/base/driver/chained-bft/storage/qc_tree.go, kernel/consensus/consensus_factory.go, kernel/consensus/consensus_impl_interface.go, kernel/consensus/consensus_interface.go, kernel/consensus/pluggable_consensus.go, kernel/consensus/pluggable_consensus_test.go, kernel/consensus/step_consensus.go, kernel/engines/xuperos/agent/rely.go, kernel/engines/xuperos/common/context.go, kernel/engines/xuperos/common/interface.go, kernel/engines/xuperos/miner/miner.go, kernel/engines/xuperos/miner/sync.go, kernel/engines/xuperos/reader/consensus_info.go
This pull request used to fix bugs consensus while upgrade.
1. Consensus can not upgrade to pow;
2. Consensus startHeight equal to triggerHeight+1;
3. Use `SwitchConsensus` while consensus upgrade；
4. Consensus will not start until to height >= Consensus startHeight.
=> fix consensus upgrade bugs

bcs/consensus/pow/pow.go, bcs/consensus/pow/pow_test.go, bcs/consensus/single/single.go, bcs/consensus/single/single_test.go, bcs/consensus/tdpos/tdpos.go, bcs/consensus/tdpos/tdpos_test.go, bcs/consensus/xpoa/xpoa.go, bcs/consensus/xpoa/xpoa_test.go, kernel/consensus/base/driver/chained-bft/storage/qc_tree.go, kernel/consensus/consensus_factory.go, kernel/consensus/consensus_impl_interface.go, kernel/consensus/consensus_interface.go, kernel/consensus/pluggable_consensus.go, kernel/consensus/pluggable_consensus_test.go, kernel/consensus/step_consensus.go, kernel/engines/xuperos/agent/rely.go, kernel/engines/xuperos/common/context.go, kernel/engines/xuperos/common/interface.go, kernel/engines/xuperos/miner/miner.go, kernel/engines/xuperos/miner/sync.go, kernel/engines/xuperos/reader/consensus_info.go
=> fix consensus upgrade bugs (#312)

bcs/consensus/xpoa/schedule.go
=> add consensus log

bcs/consensus/xpoa/schedule.go
=> add consensus log (#314)

kernel/consensus/pluggable_consensus.go
不允许从pow共识升级为其他共识
升级共识时，如果当前共识时pow则直接返回升级失败
当前共识为pow共识，升级共识会显示失败
=> 当前共识如果是pow类共识，则不允许升级

bcs/consensus/tdpos/kernel_contract_test.go
从release-v5.2同步提交版本559b082同步单元测试判断结果到release-v5.1
=> fix tdpos contract unittest error

bcs/contract/evm/state.go, kernel/contract/sandbox/xmcache.go
see https://github.com/xuperchain/xupercore/pull/210/files  for more details
=> contract: add transfer support to evm contract

bcs/contract/evm/state.go, kernel/contract/sandbox/xmcache.go
=> backport: contract: add transfer support to evm contract (#318)

bcs/contract/evm/state.go, kernel/contract/sandbox/xmcache.go
=> backport:  contract: add transfer support to evm contract (#318)

bcs/ledger/xledger/state/tx_verification.go
=> add log for tx verify failed

bcs/contract/xvm/aot_creator.go, bcs/contract/xvm/legacy_test.go
update legacy determining criterion
=> bugfix: update legacy determining criterion

kernel/contract/config.go
=> config: update memory grow enable  config key name

kernel/contract/manager/config.go, kernel/engines/xuperos/config/config.go
=> config: add yaml tag support in configure parser

kernel/contract/manager/config.go, kernel/engines/xuperos/config/config.go
=> [backport] config: add yaml tag support in configure parser (#336)

bcs/contract/xvm/hxvm.go
=> contract: add hxvm support to webassembly contract using tier up technique

kernel/contract/proposal/utils/utils.go
Solve the problem that some user tokens are not unlocked after the proposal ends
=> fix proposal prefix

bcs/contract/xvm/hxvm.go, bcs/ledger/xledger/state/xmodel/xmodel_verify.go, go.mod
两笔交易引用同一个key时，并发提交，XMdel检查读集合时从状态机查询数据，而不是batch cache，因为batch cache是给执行区块时用的。
=> post tx xmode check from db not batch cache

kernel/contract/proposal/govern_token/govern_token_contract.go
fix governToken transfer to self error
=> fix governToken transfer to self error

example/xchain/auto/build_xvm.sh, example/xchain/hack/build_xvm.sh
=> fix xvm dependency to v0.1.0

bcs/contract/native/runtime_docker.go
=> fix docker stop error

kernel/engines/xuperos/engine.go, kernel/engines/xuperos/parachain/context.go, kernel/engines/xuperos/parachain/parachain_contract.go
=> fix stopped parachain question #350

kernel/engines/xuperos/engine.go
=> fix load parachain error question #359

bcs/contract/evm/address.go, bcs/contract/evm/address_test.go, bcs/contract/evm/state.go, bcs/ledger/xledger/state/tx_verification.go, kernel/contract/bridge/context.go, kernel/contract/bridge/contract_manager.go, kernel/contract/bridge/xbridge.go, kernel/contract/context.go, kernel/engines/xuperos/chain.go
=> fix parachain evm

bcs/ledger/xledger/state/state.go, bcs/ledger/xledger/state/tx_verification.go, kernel/engines/xuperos/chain.go, kernel/engines/xuperos/reader/contract_info.go
添加根据合约名字查询合约信息接口
state 增加接口，contract_info 增加接口
=> add GetContractDesc method

bcs/network/p2pv1/server.go, bcs/network/p2pv2/server.go
- Improve TroubleShooting for bind address error
- Fix code style
close #389
=> Print network address error message in log

.github/workflows/pre-commit.yml, .pre-commit-config.yaml
Enable pre-commit for PR
@see #395
=> Support pre-commit

.github/workflows/golangci-lint.yml, .github/workflows/pre-commit.yml, .golangci.yaml, kernel/engines/xuperos/event/block_store_mock_test.go, kernel/engines/xuperos/event/block_topic.go, kernel/engines/xuperos/event/builder_test.go, kernel/engines/xuperos/event/filtered_block_iterator.go, kernel/engines/xuperos/event/router.go, kernel/engines/xuperos/event/router_test.go
Fix #407 
- Remove unused code
- Rename files for test and mock code as test file
- Deal with error
- Fix typo
- Improve readability
- Enable go lint for all branches
=> Fix kernel/engines/xuperos/event 

.github/workflows/golangci-lint.yml, .golangci.yaml, kernel/engines/xuperos/asyncworker/asyncworker_test.go, kernel/engines/xuperos/net/client.go, kernel/engines/xuperos/net/net_event.go, kernel/engines/xuperos/net/validata.go
close #405 
- Deal with missing error
- Extract methods
- Remove dead code
- Rename receiver
- Fix typos
- Refine import
- Improve readability
- Expand the scope of inspection
=> Fix kernel/engines/xuperos/net

kernel/consensus/base/common/common.go
调整ParseOldQCStorage的json.Unmarshal指针对象,使用 ```json.Unmarshal(storage, old);```
=> 调整ParseOldQCStorage的json.Unmarshal指针对象

bcs/ledger/xledger/ledger/ledger.go, bcs/ledger/xledger/state/meta/meta.go, bcs/ledger/xledger/state/meta/meta_test.go, bcs/ledger/xledger/state/state.go, kernel/contract/proposal/utils/types.go, kernel/contract/proposal/utils/utils.go, kernel/engines/xuperos/agent/rely.go, kernel/engines/xuperos/chain.go, kernel/engines/xuperos/chain_config/base/interface.go, kernel/engines/xuperos/chain_config/context.go, kernel/engines/xuperos/chain_config/types.go, kernel/engines/xuperos/chain_config/update_config.go, kernel/engines/xuperos/chain_config/update_config_manager.go, kernel/engines/xuperos/common/interface.go
支持在链运行时动态更新gasprice和 maxblocksize参数
=> Update max block size and gas price
